semi: false
useTabs: false
tabWidth: 2
printWidth: 80
singleQuote: true
trailingComma: none
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: avoid
endOfLine: lf

overrides:
  - files: '*.scss'
    options:
      singleQuote: false
