# Development server init base directory, default value is 'dev'
# Once you need custom it, be sure to add it into gitignore manually
# devDir: temp

# Build files directory, default value is dist
distDir: dist

# Config for sass
sassConfig:
  outputStyle: expanded
  precision: 5
  sourceComments: false

# Config for base64
base64Config:
  extensions:
    - svg
    - png
  deleteAfterEncoding: true
  maxImageSize: 8192 # 8kb
  # Array of exclude file or regexp
  # exclude:

# Compress css & js file, transform small png to base64
# minify: true
